services:
  chat-service:
    build: ./chat-service
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  websocket-service:
    build: ./websocket-service
    ports:
      - "8082:8082"
    depends_on:
      - chat-service

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  chat-app-network:
    driver: bridge
