services:
  chat-service:
    build: ./chat-service
    networks:
      - chat-app-network
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  websocket-service:
    build: ./websocket-service
    networks:
      - chat-app-network
    depends_on:
      - chat-service

  user-service:
    build: ./user-service
    env_file:
      - .env
    networks:
      - chat-app-network
    depends_on:
      postgres:
        condition: service_healthy

  
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chat-app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5


  mongo:
    image: mongo:latest
    networks:
      - chat-app-network
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
    depends_on:
      - chat-service
      - websocket-service
      - user-service
    networks:
      - chat-app-network

volumes:
  mongo-data:
  postgres-data:

networks:
  chat-app-network:
    driver: bridge
