services:
  chat-service:
    build: ./chat-service
    networks:
      - chat-app-network
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  websocket-service:
    build: ./websocket-service
    networks:
      - chat-app-network
    depends_on:
      - chat-service

  mongo:
    image: mongo:latest
    networks:
      - chat-app-network
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chat-service
      - websocket-service
    networks:
      - chat-app-network


volumes:
  mongo-data:

networks:
  chat-app-network:
    driver: bridge
